### ISSUE TITLE
Update SEV ioctls to be iocuddle-based types

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#112]
- [x] PlatformReset
- [x] PlatformStatus
- [x] PekGenerate
- [x] PekCertificateSigningRequest
- [x] PdhGenerate
- [x] PdhCertificateExpor
- [x] PekCertificateImport
- [x] GetIdentifier

**Comment by connorkuehl** [comment]
I'm letting this issue return to the backlog as I haven't worked on this due to prioritizing work related to the keep and shim. Furthermore, it's been brought to my attention that there needs to be some footwork to pull more types into `sev-types` and decouple them from the `openssl` feature before this task turns into more of a straight shot.
