### ISSUE TITLE
Wire up attestation flow with AESMD

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1199]
# Description:
Configure [AESMD](https://github.com/intel/linux-sgx/tree/master/psw/ae/aesm_service/config/aesmd_service) to enable attestation flow for enarx. A minimal container with the daemon is available here: https://gitlab.com/enarx/aesmd

# Acceptance Criteria:
* Configuring a host environment for Enarx is documented

**Comment by platten** [comment]
@npmccallum, could you please provide some background on this task?

**Comment by jarkkojs** [comment]
Adding link to the aesmd's source code for reference: https://github.com/intel/linux-sgx/tree/master/psw/ae/aesm_service

**Comment by jarkkojs** [comment]
I'll wire up first patches today but why it needs to be in Gitlab?

**Comment by jarkkojs** [comment]
Related: https://lore.kernel.org/linux-sgx/YfNElmmBbkw1Xpfy@iki.fi/

**Comment by jarkkojs** [comment]
I made a MR/PR (ugh):

https://gitlab.com/enarx/aesmd/-/merge_requests/1

For reference:

# How to use this container

Check that this returns `1` so that user namespace can be used without a root
account:

```bash
sysctl kernel.unprivileged_userns_clone
```

Set UID and GID ranges correctly for user namespaces:

```bash
touch /etc/subuid /etc/subgid
usermod --add-subuids 100000-165535 --add-subgids 100000-165535 jarkko
```

To start a volatile container hosting aesmd, use `podman run`:

```bash
podman run --rm \
           -it \
           --device /dev/sgx_enclave:/dev/sgx_provision \
           -v /tmp:/run/aesmd -v /tmp:/var/run/aesmd registry.gitlab.com/enarx/aesmd
```

It is necessary to expose `/dev/sgx_enclave` and `/dev/sgx_provision` so that
the architectural enclaves are able to work correctly. The UDS socket to access
aesmd will become available outside the container as `/tmp/aesm.socket`.

In order stop aesmd, follow this example transcript:

```bash
$ podman container list
CONTAINER ID  IMAGE                                   COMMAND               CREATED         STATUS             PORTS       NAMES
992bde4e2b65  registry.gitlab.com/enarx/aesmd:latest  /opt/intel/sgx-ae...  18 minutes ago  Up 18 minutes ago              admiring_greider

$ podman stop 992bde4e2b65
992bde4e2b65
```
