### ISSUE TITLE
Archive repositories currently not in use

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1237]

**Comment by bstrie** [comment]
I'm calling this a low-priority UX task, since having a lot of unnecessary repos in the Enarx organization makes the contributor experience more confusing than it needs to be.

**Comment by bstrie** [comment]
Note that by "archiving" here we mean a two-step process:

1. "Archive" the repo using Github's built in archiving feature.
2. Transfer the repo out of the github.com/enarx organization and into the [github.com/enarx-archive](https://github.com/enarx-archive/) organization.

The goal here is to clear out the Enarx organization to make it more clear what repos are active and developed, and hopefully get more eyes on the ones we care about in order to respond to e.g. PRs in a timely process. Without this it's easy for PRs to become missed, e.g. https://github.com/enarx/ciborium has had open PRs for a few months that nobody noticed. And we can't just rely on Github's natural sort ordering to float active repos to the top, because Dependabot files PRs automatically and obscures real activity.

A list of repos that are already "Archived" via Github, but need to be transferred to enarx-archive:

* https://github.com/enarx/enarx-keepldr
* https://github.com/enarx/sevctl
* https://github.com/enarx/sev
* https://github.com/enarx/packet.com
* https://github.com/enarx/docs
* https://github.com/enarx/sallyport
* https://github.com/enarx/enarx.github.io

A list of repos that *appear* to be archivable, in that they do not appear to be actively used by the Enarx project. Before actually archiving these, we should first clear it with Nathaniel. Checked boxes indicate repos that have been cleared or archival:

* [ ] https://github.com/enarx/client
* [ ] https://github.com/enarx/enarx-wasmldr
* [ ] https://github.com/enarx/enarx-shim-sgx
* [ ] https://github.com/enarx/telestes
* [ ] https://github.com/enarx/koine
* [ ] https://github.com/enarx/wasm5
* [ ] https://github.com/enarx/enarx-heap
* [ ] https://github.com/enarx/fedora-kernel
* [ ] https://github.com/enarx/demo
* [ ] https://github.com/enarx/enarx-keepmgr
* [ ] https://github.com/enarx/sev-iocuddle
* [ ] https://github.com/enarx/commisery-action
* [ ] https://github.com/enarx/lebicon
* [ ] https://github.com/enarx/codicon
* [ ] https://github.com/enarx/endicon
* [ ] https://github.com/enarx/signrel
* [ ] https://github.com/enarx/uabs
* [ ] https://github.com/enarx/rfcs
* [ ] https://github.com/enarx/copr
* [ ] https://github.com/enarx/bot
* [ ] https://github.com/enarx/rpceval
* [ ] https://github.com/enarx/frenetic
* [ ] https://github.com/enarx/bot-test
* [ ] https://github.com/enarx/nightly-features
* [ ] https://github.com/enarx/snp

**Comment by bstrie** [comment]
This is complete. It's possible that we may find that we can archive even more repos as we continue to regularize the Enarx organization's Github presence, but those will be tackled on a case-by-case basis.
