### ISSUE TITLE
[Infrastructure]: Linting: Check for newline at end of file.

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Ensure that files end with a newline character.

**Comment by Ankita13-code** [comment]
HI @rjzak! Although the cargo fmt command itself adds a newline character to each line of a rust project, for a lint check shall we use clippy plugin for this purpose?

**Comment by rjzak** [comment]
The Github actions should require Clippy to run successfully in order for a PR to be allowed.

It seems this should be done via this file: https://github.com/enarx/enarx/blob/main/.github/workflows/lint.yml, so I suspect this is likely a stale issue.

Test and see what happens. Submit a PR without a newline at the end. If the tests fail due to a Clippy or `cargo fmt` error, close this issue as completed (but check the actions output to confirm the reason for the test failure, since a lot of the unit tests are failing recently for unknown reasons). If the tests pass, then you've got something you can work on.
