### ISSUE TITLE
[Infrastructure]: Migrate to Cargo binary dependencies

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Migrate build system to use the new cargo binary artifacts facility.

**Comment by bstrie** [comment]
I'm looking into this again. Previous attempts were stymied by https://github.com/rust-lang/cargo/issues/10431 and https://github.com/rust-lang/cargo/issues/10452 , which are fixed on nightly via https://github.com/rust-lang/cargo/pull/10433 (though we will need to bump our toolchain to get the fix). The first step will be to make wasmldr a binary artifact (since the shims are blocked on making unknown-none a Tier 2 platform: https://github.com/enarx/enarx/issues/1528). Currently I'm seeing some strange build failures that I will need to minimize and diagnose; it would not surprise me if there were still lingering bugs in the implementation of binary artifacts (which is fine; putting this feature through its paces is one of our goals here).

**Comment by bstrie** [comment]
wasmldr has been made a binary artifact, although with complications; see the extensive comment at https://github.com/enarx/enarx/pull/1604 for details. In particular we encountered several bugs with binary dependencies that either needed to be worked around or endured. I've minimized the remaining bugs and filed them with Cargo:

1. https://github.com/rust-lang/cargo/issues/10525
    * This bug is mildly concerning due to how unclear the underlying cause is and the subtle ways in which it is triggered. However, as best we can tell so far its only result is compilation errors rather than anything extremely concerning such as miscompilations. We should not let this block our attempts to continue migrating to binary dependencies, but we should keep it in mind.
3. https://github.com/rust-lang/cargo/issues/10526
    * This bug is a soft blocker for porting the shims to binary dependencies, because we don't want to include both shims in the Enarx binary. However, it's not impossible to work around this, so in theory we could proceed with porting the shims.
5. https://github.com/rust-lang/cargo/issues/10527
    * This bug is something that we've simply decided to endure for the time being. Anyone making changes to any binary dependency will need to keep this in mind while developing. Notably this isn't a problem for anything that builds from scratch, e.g. CI.
