### ISSUE TITLE
Use once_cell::sync::Lazy in preparation for stdlib inclusion

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1517]
Currently the stdlib is in the process of acquiring a standard type for lazy initialization, by upstreaming the types in the once_cell crate. Port our current lazy initialization (via `spinning::Lazy`) to `once_cell::::sync::Lazy`. Once this is done it should be trivial to port it to the stdlib version once stabilized (and I suspect we can even push it over the line into stabilization relatively quickly if we wanted to). This will involve tinkering with the synchronization logic (`RwLocked`), but once it's complete I think we'll have a better story regarding the safety of our mutable statics.

**Comment by Freax13** [comment]
I'd like to work on this issue.

**Comment by Freax13** [comment]
> Port our current lazy initialization (via `spinning::Lazy`) to `once_cell::::sync::Lazy`.

One big problem with that is that `once_cell::sync::Lazy` is not available in no_std, so we'd have to use the unsynchronized variants. Since `once_cell::unsync::Lazy` is not `Sync`, we'd have to wrap them in a `Mutex`. which will no longer allow us to access the data concurrently or use another synchronization primitive like `RwLock` on top of `Lazy`. This is also prone to deadlocks because we need to take locksall the time even though we want to read immutable data.
Note that wrapping `once_cell::unsync::Lazy` in a `RwLock` won't work because unlike `Mutex` `RwLock` requires the wrapped type to be `Sync`.

Don't get me wrong, it's doable to convert all uses of `spinning::Lazy` to `once_cell::unsync::Lazy` like this (see https://github.com/Freax13/enarx/commit/5d95112b8dd8162729682ea0d84cfa66db851a66 for most of the required changes) but IMO this makes the code worse.

I'd like to propose just changing the code that has access to std to use `once_cell` and keep using `spinning` for the shims.

**Comment by bstrie** [comment]
Interesting, from reading the docs for once_cell it's not obvious that the `unsync` module is no-std while the `sync` module isn't. I had assumed that it would be using a spinlock internally, but I suppose it's also a reasonable design for it to ask you to bring your own spinlock. I'll leave the decision to Harald, who has more experience with the shims and with the spinning crate.

**Comment by haraldh** [comment]
> I'd like to propose just changing the code that has access to std to use `once_cell` and keep using `spinning` for the shims.

Yes, makes sense.

And for the shims, when we implement multi-threading, we have to write our own RwLock and Mutexes anyway with the help of proxying to the host with the `futex()` syscall after some manual spinning.
