### ISSUE TITLE
The git pre-push hooks don't work

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#164]
I did a rebase on upstream master. Then I created a new branch and added a commit. Then I pushed it to my repo. The pre-push hooks did not appear to run. Do they need to be manually enabled? If so, this needs to be documented.

**Comment by mbestavros** [comment]
@npmccallum Since we put our tests in a new `hooks` directory, I had to run `git config core.hooksPath hooks` to make git recognize them as hooks. I ran this with @lkatalin and was able to verify that the above command makes the hooks work (where they didn't before). I'd forgotten about the command when I made my PR, apologies.

The [original issue](https://github.com/enarx/enarx/issues/43) documented that we wanted everything in a custom `hooks` directory, and included the corresponding command to make the new directory work. If developers run that command, hooks would work fine -- but that makes the tests opt-in and non-default. I'm not sure we want that.

The other alternative would just be to move everything in `hooks` to the default `.git/hooks` directory. That would mean tests would run on every machine by default -- though the tradeoff is less visibility.

I'm personally in favor of the second option (people will use defaults more than options), but I'm open to opinions.

**Comment by npmccallum** [comment]
@mbestavros The scripts in the `.git/hooks/` directory are not managed by git. So that is not an option. I'm pretty sure we have to have scripts be opt-in, otherwise it would be too easy for me to run code on every fork of Enarx.

**Comment by mbestavros** [comment]
@npmccallum Good to know. In that case, I think we should document the opt-in command at least on the How to Contribute wiki page, if not also the README.

**Comment by npmccallum** [comment]
@mbestavros That seems like an adequate resolution for this issue.

**Comment by mbestavros** [comment]
@npmccallum Closing this, then.
