### ISSUE TITLE
[Bug]: Enarx fails to setup connection with C workloads

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```
Error: failed to setup connection stream

Caused by:
    0: failed to connect to endpoint
    1: Connection refused (os error 111)
```

### Expected Behaviour

Either a success or clear error message on what the user did wrong

### Environment Information

enarx 0.6.4

### Steps To Reproduce

1. Compile https://github.com/enarx/codex/blob/606bf6b406e26f80fb62556d89477da634f2d82a/demos/chat-client/c/main.c#L1-L50 to wasi (or grab the compiled WASM from https://github.com/enarx/codex/suites/8901703376/artifacts/407369244 at https://github.com/enarx/codex/actions/runs/3299794462)
2. Run in Enarx with https://github.com/enarx/codex/blob/ff9d854d2ceb3840586d85901174802a9486cf15/demos/chat-client/Enarx.toml

**Comment by rvolosatovs** [comment]
cc @rjzak @unwosu6

**Comment by haraldh** [comment]
Is something listening on the destination port?

**Comment by haraldh** [comment]
The bug is in the server. Client works fine, if the server is running/restarted.

❯ enarx run --wasmcfgfile server/Enarx.toml server/main.wasm 
> 01GG4DH4WP9BMY9ZJVJCBZWVTA joined the chat
> 01GG4DH4WP9BMY9ZJVJCBZWVTA: ljhgljkg
thread 'main' panicked at 'failed to park: Os { code: 29, kind: Uncategorized, message: "I/O error" }', /nix/store/s368wavbcpbx1ss20n096k6xg0q343vi-dependencies/tokio-1.20.0-56be5286ee9548c483b91b7593ededcd34c5da0b/src/runtime/basic_scheduler.rs:326:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: KVM error: Shutdown

❯ enarx run --wasmcfgfile server/Enarx.toml server/main.wasm 
> 01GG4DJPAP8T3AGNDCHAJ81MWA joined the chat
> 01GG4DJPAP8T3AGNDCHAJ81MWA: jhgjhg
> 01GG4DJPAP8T3AGNDCHAJ81MWA: jhg#
thread 'main' panicked at 'failed to park: Os { code: 29, kind: Uncategorized, message: "I/O error" }', /nix/store/s368wavbcpbx1ss20n096k6xg0q343vi-dependencies/tokio-1.20.0-56be5286ee9548c483b91b7593ededcd34c5da0b/src/runtime/basic_scheduler.rs:326:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: KVM error: Shutdown

**Comment by rjzak** [comment]
Running the release version of 0.6.4 worked with the C version of my Wordle clone https://github.com/rjzak/web_wordpuzzle/tree/main/C
