### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#335]
We need to adopt a Code of Conduct. This needs to be coordinated with our CCC membership.

**Comment by MikeCamel** [comment]
The CCC is adopting 2.0, and recommending the same for all projects.  We should go with 2.0.

**Comment by axelsimon** [comment]
Contributor Covenant v2.0 is now our Code of Conduct (cf. [this PR](https://github.com/enarx/.github/pull/2)).

**Comment by axelsimon** [comment]
> However, i need to figure out why it's not showing up automatically on other repos, although the Github documentation [says](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file):
> 
> > You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any public repository owned by the account that does not contain its own file of that type.

Ok, i've re-read that documentation page, and i just don't understand why on, for instance, the [sevctl](https://github.com/enarx/sevctl) repo nothing shows up, even though it doesn't have its own CODE_OF_CONDUCT.md. According to the documentation, it should work:

> You can add default community health files to the root of a public repository called .github that is owned by an organization or user account.
> 
> GitHub will use and display default files for any public repository owned by the account that does not have its own file of that type in any of the following places:
> 
>     the root of the repository
>     the .github folder
>     the docs folder

If anyone has a clue, it would be much appreciated. I'll keep investigating in the meantime.

**Comment by axelsimon** [comment]
Created a new public [test repo](https://github.com/enarx/this-is-a-test), to see if the default community files from the .github repo would appear there. Nope.
A ticket is being raised with Github support right row.

**Comment by axelsimon** [comment]
Github support clarified the behaviour of the .github repo: it doesn't show the community health files such as CODE_OF_CONDUCT.md in the other repositories directly, but it references them when opening a new issue, for instance.
Cf. the following:
![](https://enterprise.githubsupport.com/attachments/token/XbkdW1Bo8lSn9IjfXjZNFLZDF/?name=enarx-new-issue.png)

Should we also edit the issue templates so that they make a reference to them? @mbestavros, what do you think?
I'm not sure that's necessary, as even if it's not one's first issue, the code of conduct is still linked at the bottom right, in the "Helpful resources" section (below labels, milestones etc.).

**Comment by mbestavros** [comment]
This is now in place, so we're closing it.
