### ISSUE TITLE
goblin vs xmas-elf

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#425]
We are currently using two ELF parsers: `goblin` and `xmas-elf`. We need to pick one and remove the other one. Someone needs to research this and make an argument as to why we should pick one over the other.

**Comment by connorkuehl** [comment]
I have some implementation experience with `goblin` in #572. I will update this issue once I have some more experience with it as we iterate on code leading up to loading the end-user's application into the keep.

**Comment by connorkuehl** [comment]
We are going with `goblin` for now because:

* `goblin`'s [documentation](https://docs.rs/goblin/0.2.3/goblin/) contains descriptions of the API it provides; `xmas-elf`'s [documentation](https://docs.rs/xmas-elf/0.7.0/xmas_elf/) does not provide descriptions beyond what readers can infer from type/method names.
* `goblin` appears to be [consistently active](https://github.com/m4b/goblin/graphs/code-frequency) whereas `xmas-elf` is [inactive](https://github.com/nrc/xmas-elf/graphs/code-frequency) and has a number of unanswered issues piling up.
* `goblin` and `x-mas` elf are both `no_std`
* `goblin` and `xmas-elf` both provide the required features for us to load an ELF binary, however, due to the above comparisons, I have found `goblin` easier to ramp up on and it has been my experience that an active upstream results in a better downstream experience.
