### ISSUE TITLE
Mentorship request for Kathryn W. 

### ISSUE THREAD

**Issue by CyberEpsilon** [enarx/enarx#426]
**About**
Tell us a bit about yourself! How did you find the project? What's your favorite IT Crowd episode? etc.

- I'm a student at Columbia University studying computer science. Currently, I've taken leave (in part to save money ;) ) to spend time working as an Information Systems Security Specialist at the Columbia University Medical Center. 

- I first heard about Enarx via an Empire Hacking webinar and decided to attend the public team meetings to find out more about the project. I have never contributed to open source software, so this is an exciting new venture for me. 

**Skills**
Tell us a bit about your background: what skills you have, relevant prior
experience, etc. Don't copy-paste your entire resume -- this is not an
interview! We just need enough to get the ball rolling.

- Languages Studied: Java, C, Python 
- Languages/Topics in Progress: C Data Structures, Assembly, Javascript, Rust
- Personal study in Progress: malware & binary analysis; penetration testing
- OS: Linux, Ubuntu, Kali Linux, Windows, Unix, Mac, etc.
- Tools: Visual Studio, Anaconda, MacVim, other common sec CLI tools, etc.

**Interest areas**
Are there any particular parts of the project you would like to contribute to?

- At this time, I'd like to contribute to any project that will allow me become to more familiar with computer architecture, operating systems design/concepts(e.g. Linux Kernel Development) and variants of assembly languages(i.e. WASM); SDLC, etc. 
- I also don't mind starting with smaller/"easier" projects or those that cover areas other than what I've mentioned.

**Comment by lkatalin** [comment]
Thanks for this great write-up! Your skills and interests sound like a great fit here for sure. 

I'm happy to help out if you have questions or want more of an organized orientation to go through the existing codebase.

**Comment by connorkuehl** [comment]
Hi Kathryn!

I'm also really interested in kernel development and computer architecture! There are a lot of  interesting opportunities in Enarx to hack on the hardware/software interface. Our Enarx keep implementation for SEV depends on a microkernel (in Rust, of course) and the goal is to keep it tiny and digestible so it's easily audited. It'd be a great kernel to start learning more low-level systems concepts especially as a supplement self-studying the Linux kernel.

We also contribute patches to the upstream Linux kernel when the opportunity presents itself, and Nathaniel participates in the review process for the Intel SGX Linux patch set on the upstream mailing list.

If any of the above sounds like fun to you, please don't hesitate to let us know! I spend most of my time at Enarx working on the SEV and kernel-related components and I'd be happy to team up with you on some of our github issues.

I'm based on the west coast, so I'm usually "around" from 7am-4pm or 5pm PDT on weekdays. It's great that you're already in our gitter channel, since that's the best place to find us for discussions on Enarx development outside of our standups.

**Comment by mbestavros** [comment]
Great to have you here, Kathryn! We love to see people getting involved on their own.

As for my part, I own our project infrastructure -- so think CI, testing, and automatic project organization. Recently, I've been doing a lot of work with the Github Actions API around project automation. Perhaps not as hardcore as our kernel/TEE development, but it's a lot of fun!

I'm Boston-based and generally available throughout the day ET. As Connor mentioned, Gitter is likely the best place to find me.

**Comment by connorkuehl** [comment]
Hey @CyberEpsilon!

I think a good jumping-off point for the project would be:

1. Bookmark the [Learn Rust](https://www.rust-lang.org/learn) page. I notice you already have some experience with C-like languages, so some snippets of Rust code might seem some familiar and others might seem kind of alien. I recommend reading through ["The Book"](https://doc.rust-lang.org/book/). I always got my best value from this by typing out all the examples and playing around with them. Be patient with this process :-) I've probably "re-learned" Rust like 3 times. The learning curve is weird at times but not impossible.
1. Get access to a Linux box/partition/virtual machine. Many of us use Fedora so it might just be simpler to use what everyone else is using, but if you prefer another Linux distro I'm sure we can figure out most issues that arise.
1. Stress test our [Enarx development environment setup](https://github.com/enarx/enarx/wiki/How-to-contribute#enarx-development-environment-set-up) section on our wiki. The documentation should guide you to a point where you can build the entire Enarx project (`cargo build`) and run its test cases (`cargo test`). If that is not the case, feedback on what errors you've encountered are extremely valuable. Feel free file a GitHub issue against our repo with the `documentation` label to let us know what kind of errors you run into.
1. Read the [Enarx Syscall Proxy](https://github.com/enarx/enarx/wiki/Enarx-Syscall-Proxy) wiki page. This is a key piece of some of the work that is currently in-progress in the Enarx project. It doesn't have to gel right away, but it's good to have this problem area drifting around somewhere in your mind.
1. Finally, read some other [architectural/component pieces in the wiki](https://github.com/enarx/enarx/wiki). 

I realize none of the above has us hacking on Enarx issues yet, but I think it's one of the shortest paths to that jumping off point :-)

I am off tomorrow (Apr 24) but on Monday I'll be back with some issues that should be fun to work on. Obviously there's no deadline or anything here so just go at a pace that works for you. I can't emphasize that enough. I'll also have that list of some of my favorite OS concepts books that I promised on the Bluejeans call earlier today.

And of course, [the gitter](https://gitter.im/enarx/dev) is always a good place to be.

**Comment by connorkuehl** [comment]
Hi @CyberEpsilon!

I did some spelunking and I think these issues are good jumping off points to introduce you to different layers of SEV inside of Enarx and a good way to gain some experience with Rust.

The first issue is related to some cleanup to keep our code passing lints, but the other two issues are contributing to a library known as `sev-types` which we ultimately hope to publish as an independent crate for others that want to write SEV-related code. `sev-types` is also going to be heavily used by our SEV components, so your code will impact lots of the Enarx SEV subsystem. 

0. #445 
0. #446 
0. #447 

If any of these sound good to you, go ahead and comment on them saying you'd like to work on them. I think at that point I can assign the issue to you (I don't think you can self-assign the issue due to GitHub permissions).

A lot of our kernel code for SEV is currently on the `demo2020` branch and my top priority is getting it merged into `master`. So while there's not a lot of SEV kernel-hacking to do on the `master` branch just yet, I'd encourage you to read the PRs that are bringing that code in and to participate in their reviews if you feel so inclined. #416 and #432 are examples of these kinds of PRs I'm working on.

Finally, as promised, here are some of my favorite OS/kernel books (they're available online for free).

I just want to preface this by saying that self-studying kernel development should feel more like a slow drip. I don't recommend burning through these in a week. I'm still learning new things about kernel concepts and practice all the time, and I think that will be the case for many, many, many years.

- [Operating Systems: Three Easy Steps](http://pages.cs.wisc.edu/~remzi/OSTEP/) - fantastic textbook about OS theory
- [Linux Device Drivers 3rd Edition](https://lwn.net/Kernel/LDD3/) - really great introduction to working on the Linux kernel. It primarily focuses on device drivers (which make up a staggering percentage of the kernel) but it will also touch on core subsystems, which I found useful. This was written for the 2.6 kernel but trust me, many of the core ideas are still relevant and with a little bit of googling you can get past any API changes that have occurred since the book was written.
- [xv6](https://pdos.csail.mit.edu/6.828/2012/xv6.html) - a learner's operating system. This is the OS that I played with during my operating systems course at university. If you explore that page you might be able to find information on the class's reading schedule/resources and maybe projects. I haven't explored their course content too much. I would highly recommend checking out the source code and [reading the walkthrough they wrote](https://pdos.csail.mit.edu/6.828/2012/xv6/book-rev7.pdf). It is excellent. It seems very large at first, but once you settle in, you might find this "bite-sized" kernel to be a fun learning tool.

Here are some non-free books:

- [CODE](https://www.goodreads.com/book/show/44882.Code) - I love this book. This is a really accessible introduction to computer organization/architecture.
- [Linux Kernel Development](https://www.goodreads.com/book/show/8474434-linux-kernel-development) - This is a really good overview of the Linux kernel. Again, if I recall correctly the version of the kernel that it talks about is a little dated but many of the core concepts are relevant and useful.

The point at which you'll be able to work on a kernel comes much faster than you would assume. Don't paralyze yourself by reading decades and decades of books on the Linux kernel. [Eventually, you just have to dive in](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/). Also see [this email](https://lists.kernelnewbies.org/pipermail/kernelnewbies/2017-April/017765.html) and [kernelnewbies](https://kernelnewbies.org/).

**Comment by CyberEpsilon** [comment]
Thanks a lot, Connor!

**Comment by axelsimon** [comment]
>  3\. Stress test our [Enarx development environment setup](https://github.com/enarx/enarx/wiki/How-to-contribute#enarx-development-environment-set-up) section on our wiki. The documentation should guide you to a point where you can build the entire Enarx project (`cargo build`) and run its test cases (`cargo test`). If that is not the case, feedback on what errors you've encountered are extremely valuable. Feel free file a GitHub issue against our repo with the `documentation` label to let us know what kind of errors you run into.

Just a quick note that the Enarx development environment setup has moved to a different section on our wiki, its [own page](https://github.com/enarx/enarx/wiki/How-to-contribute-code#enarx-development-environment-set-up), to be specific.

**Comment by CyberEpsilon** [comment]
Ok, got it!

**Comment by connorkuehl** [comment]
I forgot to close this issue with the pull request, but @CyberEpsilon's first PR was merged a little while ago! :tada:
