### ISSUE TITLE
Sorting Hat - Workflow Automation Bot

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#52]
We need a bot that runs on GitHub Action hooks to ensure that issues and pull requests have their metadata normalized. In particular, the bot needs to place issues/PRs into their respective projects when a tag is applied. Likewise, when the tag is removed, they should be removed from the respective projects.

**Comment by mbestavros** [comment]
I've been doing some investigation into potential options for project automation; here are a few things I've found.

**[Github Actions Automate Projects](https://github.com/takanabe/github-actions-automate-projects)**

This is by far the most powerful pre-made action I've encountered: it (in theory) allows you to craft conditions based on any part of the Actions webhook, and then move issues or PRs into project columns based on those conditions.

The catch: it doesn't work yet. The author seems to have [manually blocked](https://github.com/takanabe/github-actions-automate-projects/blob/master/issues.go#L47-L51) handling any condition that's not opening a new issue or PR. I've been trying to get a fork working to try and build a patch that removes this block; that is WIP.

**A custom [Probot app](https://github.com/probot/probot)**

From the repo: "Probot is a framework for building GitHub Apps in Node.js, written in TypeScript."

It may require a little more development time, but I think this has the best potential to hit all our automation goals -- including those not covered by existing apps. The example app seems simple enough to manipulate into something that could work for a few of our automation use cases, so that might be a good place to start.

**A third-party project management solution such as [ZenHub](https://github.com/marketplace/zenhub/)**

Third-party tools will likely provide a lot of functionality straight away, but won't integrate with Github's built-in boards. This is potentially poor UX for newcomers; I'm personally a fan of making Github's boards work.

**Comment by mbestavros** [comment]
Our current plan is to utilize [Mergeable](https://github.com/mergeability/mergeable) for our project automation.

It doesn't yet support the actions we need, but upstream seems receptive to patches. The hope is that we'll be able to implement those actions ourselves, get it merged, and then actually use it.

**Comment by mbestavros** [comment]
Update time!

We're no longer planning on using Mergeable. We found that it wasn't as flexible as we'd hoped, and it would be difficult to accomplish what we wanted to. Instead, we'll be implementing the actions we want ourselves, running as scripts as part of a Github Action. The first such example is merged: #360. We plan on implementing new functionality similarly.

**Comment by platten** [comment]
We will consider other kinds of automation going forward.
