### ISSUE TITLE
Use builtin cargo-make environment variable for finding the workspace root

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#599]
Right now we use [`git` to deduce where the root of the workspace is](https://github.com/enarx/enarx/blob/master/Makefile.toml#L29) to construct absolute paths to some of our CI scripts.

However, this is made redundant by `cargo-make`'s builtin environment variable that already does this:

> `CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY` - The original working directory of the workspace. Enables workspace members access to the workspace level `CARGO_MAKE_WORKING_DIRECTORY`.

Furthermore, our current approach has a problem because it depends on `git`. This isn't an issue for the common case, but GitHub does allow people to download a copy of the repo _without_ any of the `.git/` data. This dependency on `git` will prevent people from building the Enarx repo if they have downloaded a copy of the source without `git`.

```bash
$ curl -LOk https://github.com/enarx/enarx/archive/master.zip
$ cd enarx-master
$ cargo make
[cargo-make] INFO - cargo make 0.30.6
[cargo-make] ERROR - Error while executing command, exit code: 128
[cargo-make] WARN - Build Failed.
$ git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
$ echo $?
128
```

Switch our `Makefile.toml` to use the `CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY` to replace `CARGO_WORKSPACE_ROOT`.

**Comment by ziyi-yan** [comment]
I tried out use `CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY` for replacement. But it turns out that it refers to the root directory of each member, instead of the root directory of the project. I think it's because there is no real workspace defined in the root directory. It is an emulated workspace by the option `CARGO_MAKE_WORKSPACE_EMULATION` from `cargo-make`. So I use `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` instead and it works.
