### ISSUE TITLE
How to set up Enarx and how to enable SGX in it?

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#659]
Hi, all,

I am a new user of Enarx, I read all Enarx wikis but still has some questions about Enarx:
- How to install Enarx? What is the HW and OS/SW requirement? The right usage of Enarx?
- How to build and run test case of Enarx?
- How to enable SGX on Enarx, and how to run SGX test case?

Does Enarx has a user guide about these basic usages? Thanks a lot~~

**Comment by connorkuehl** [comment]
> Hi, all,

Hi @xiaonan-INTC!

> How to install Enarx? 

Enarx is currently under development, so we have no release binary packages for anyone to install yet.

> What is the HW and OS/SW requirement? 

Check out the [TEE hardware support](https://github.com/enarx/enarx/wiki/TEE-hardware-support) wiki page.

As far as software: the Enarx runtime components will have to run on a Linux distribution since we program closely against the Linux kernel interface. However, the Linux kernel does not yet officially have Intel SGX driver support, but it does have AMD SEV driver support. So if you plan to build and run Enarx from source, you'll need to install [a patched Fedora 32 kernel](https://copr.fedorainfracloud.org/coprs/npmccallum/enarx/builds/) if you plan on using Intel SGX. Alternatively, you can patch your own kernel. [The Intel SGX patches are on Patchwork](https://patchwork.kernel.org/project/intel-sgx/list/).

> The right usage of Enarx?

> How to build and run test case of Enarx?
> Does Enarx has a user guide about these basic usages? Thanks a lot~~

See [these instructions for setting up a development environment](https://github.com/enarx/enarx/wiki/How-to-contribute-code#enarx-development-environment-set-up) and [these instructions for building and running various things](https://github.com/enarx/enarx/wiki/How-to-contribute-code#cargo-make).

> How to enable SGX on Enarx, and how to run SGX test case?

Assuming your development environment has been set up properly and your hardware supports SGX, you can run the SGX integration tests with `cargo make integration`. They will automatically detect you're running on SGX and will run the SGX-specific integration tests.

**Comment by xiaonan-INTC** [comment]
@connorkuehl 

Thanks for your guidance,

I am trying to enabling Enarx on Fedora 31, but still met an issue that when installing rust from official command "curl https://sh.rustup.rs -sSf | sh", it always showed:
----------------------------------------------------------------------------------------------------------------------------------------
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/home/sgx/.rustup/tmp/mwu4os4i1wuzmer8_file'
error: caused by: failed to make network request
error: caused by: error sending request for url (https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256): operation timed out
error: caused by: operation timed out
----------------------------------------------------------------------------------------------------------------------------------------
I wanna install rust by source code, what should I choose from https://forge.rust-lang.org/infra/other-installation-methods.html - Standalone installers? x86_64-unknown-linux-gnu or x86_64-unknown-linux-musl and why?

**Comment by xiaonan-INTC** [comment]
@connorkuehl

Thanks for your guidance,

I am trying to enabling Enarx on Fedora 31, but still met an issue that when installing rust from official command "curl https://sh.rustup.rs -sSf | sh", it always showed:
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/home/sgx/.rustup/tmp/mwu4os4i1wuzmer8_file'
error: caused by: failed to make network request
error: caused by: error sending request for url (https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256): operation timed out
error: caused by: operation timed out
I wanna install rust by source code, what should I choose from https://forge.rust-lang.org/infra/other-installation-methods.html - Standalone installers? x86_64-unknown-linux-gnu or x86_64-unknown-linux-musl and why?

**Comment by connorkuehl** [comment]
@xiaonan-INTC Those are good questions to post in the [#beginners room in the Rust Discord](https://discord.gg/rust-lang) or [the Rust Users forum](https://users.rust-lang.org/). I think you'll get much better answers from them about those questions than I could give you :-)

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Those are good questions to post in the [#beginners room in the Rust Discord](https://discord.gg/rust-lang) or [the Rust Users forum](https://users.rust-lang.org/). I think you'll get much better answers from them about those questions than I could give you :-)

hi, @connorkuehl 

Thanks for your support, I have solved that rust issue, :)

But I still have an issue of enabling SGX with Enarx, I don't ensure if I can raise up a question in this https://github.com/enarx/enarx/issues
or could you point me a right url to ask for help?

My issue is:
When I download a patched Fedora 32 kernel from your url, and install it, I could not find the kernel in /boot, could you or any other guys provide a detailed steps of enabling SGX with Enarx?
Really appreciate your help, :)

**Comment by xiaonan-INTC** [comment]
> > @xiaonan-INTC Those are good questions to post in the [#beginners room in the Rust Discord](https://discord.gg/rust-lang) or [the Rust Users forum](https://users.rust-lang.org/). I think you'll get much better answers from them about those questions than I could give you :-)
> 
> hi, @connorkuehl
> 
> Thanks for your support, I have solved that rust issue, it was caused by network w/ proxy :)
> 
> But I still have an issue of enabling SGX with Enarx, I don't ensure if I can raise up a question in this https://github.com/enarx/enarx/issues
> or could you point me a right url to ask for help?
> 
> My issue is:
> When I download a patched Fedora 32 kernel from your url, and install it, I could not find the kernel in /boot, could you or any other guys provide a detailed steps of enabling SGX with Enarx?
> Really appreciate your help, :)

I am trying to install that Enarx SGX patch, :)

**Comment by connorkuehl** [comment]
> When I download a patched Fedora 32 kernel from your url, and install it, I could not find the kernel in /boot, could you or any other guys provide a detailed steps of enabling SGX with Enarx?

Did you download just a binary RPM or did you add the Copr and run `dnf upgrade`? If you're manually installing the binary packages you'll want to make sure you download and install _at least_ the following binary packages:

1. `kernel-*`
2. `kernel-core-*`
3. `kernel-modules-*`

Many people don't need `kernel-modules-extra-*` but if you notice your specific machine is missing some modules you may want to install that as well.

I recommend using the Copr repo for ease of installation. Make sure secure boot is disabled in your BIOS because these kernels aren't signed.

**Comment by xiaonan-INTC** [comment]
> > When I download a patched Fedora 32 kernel from your url, and install it, I could not find the kernel in /boot, could you or any other guys provide a detailed steps of enabling SGX with Enarx?
> 
> Did you download just a binary RPM or did you add the Copr and run `dnf upgrade`? If you're manually installing the binary packages you'll want to make sure you download and install _at least_ the following binary packages:
> 
> 1. `kernel-*`
> 2. `kernel-core-*`
> 3. `kernel-modules-*`
> 
> Many people don't need `kernel-modules-extra-*` but if you notice your specific machine is missing some modules you may want to install that as well.
> 
> I recommend adding the Copr repo via `dnf` for ease of installation. Make sure secure boot is disabled in your BIOS because these kernels aren't signed.

@connorkuehl 
Thanks a lot! I succeeded in installing that Fedora 32 patched kernel, :)
