### ISSUE TITLE
enarx-keep-sgx-shim: clock_gettime syscall

### ISSUE THREAD

**Issue by ueno** [enarx/enarx#664]
wasmtime's codegen [gathers timing information](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/timing.rs) for each compilation pass using `clock_gettime(CLOCK_MONOTNIC, ...)`. While on the host this is handled through vDSO, this turns into a normal syscall inside a Keep.

I'm not sure how to handle time information within a Keep in general, but maybe the shim could provide a stub.

**Comment by npmccallum** [comment]
@ueno TL;DR - let's implement it.

Lots of applications will need this. However, we currently have no way of implementing this without forwarding the request to the host, who could lie. I've requested strategies from the various hardware vendors. They have all assured me they are working on it. But the bottom line is that we need it sooner rather than later. So let's implement it.

**Comment by ziyi-yan** [comment]
Hi, @npmccallum @ueno ! I'd love to take this task as my first in-depth contribution to enarx codebase. What I understand now from the above discussion is that we need to implement `clock_gettime` syscall in sgx keep by forwarding it to the host. I'll start to study related code tomorrow. It would be nice if you can give me any pointers about how to get started on this task and where the code I need mostly working on is. :smile:

**Comment by npmccallum** [comment]
@ziyi-yan Absolutely. @lkatalin Could you show @ziyi-yan how to add a syscall proxy?

**Comment by npmccallum** [comment]
This syscall isn't super hard to add. The `clockid_t` can be passed unmodified. The `struct timespec` will need to be copied into unencrypted memory using the `sallyport::Block` and the address for it replaced.

**Comment by lkatalin** [comment]
@ziyi-yan Our syscall proxies for SGX are defined in [this file](https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/handler.rs). They are methods on the enclave's `Handler`. Each enclave `handler` has access to a `block` of untrusted memory (the address is passed in from the host). The `block` contains the syscall number, any arguments, and a buffer to store additional data (ex. for reads and writes) in a specific format defined [here](https://github.com/enarx/enarx/tree/master/sallyport). 

The way to proxy a syscall to the host side is to create a method on the `Handler` for the syscall. This method should create a [Request](https://github.com/enarx/enarx/blob/master/sallyport/src/lib.rs#L40) and pass this `Request` as a parameter when calling the `Handler`'s `proxy()`. 

We're currently porting these syscall proxies over to using the `Block` and `proxy()` in the `Handler`. If you don't see the `proxy()` used in the current code yet, that is why. `handler.proxy()` is taking the place of the earlier `handler.syscall()`.

If you have questions, don't hesitate to ask!

**Comment by ziyi-yan** [comment]
@lkatalin Hi, Lily. I submitted a PR after figuring out the sallyport, `proxy()` and `Block` usage.

For now, this PR has only passed the compilation on my machine. Sorry that I don't have an SGX environment yet.

Here is a snippet of [C code](https://gist.github.com/ziyi-yan/ce4bb1d838eaa6e3b6885d8ecdbf8a6a) (copied from [here](https://0xax.gitbooks.io/linux-insides/content/Timers/linux-timers-7.html)), which calls `clock_gettime()` for you, if you can help me to test it. Thanks! 😄

**Comment by lkatalin** [comment]
@ziyi-yan Thanks for your PR! We're currently working on getting a template going for testing syscalls in general. This should be merged today or early next week. In the meantime, it is possible to do a manual test. I think what you will want in order to test this manually is to construct a [payload](https://github.com/enarx/enarx/blob/master/payload/src/main.rs) that uses the Rust version of `clock_gettime()` described [here](https://docs.rs/libc/0.2.72/libc/fn.clock_gettime.html). 

If you `cargo build` this payload, you can then call it manually with `enarx-keep-sgx/target/debug/enarx-keep-sgx --code payload/target/x86_64-unknown-linux-musl/debug/payload --shim enarx-keep-sgx-shim/target/x86_64-unknown-linux-musl/debug/enarx-keep-sgx-shim`. (If the payload is in a different location, you will have to find the file path and use that.)

I can update this comment soon with the syscall test template that you can use if you want to include a test in your PR.

**Comment by ziyi-yan** [comment]
@lkatalin Thanks! Due to the lack of sgx support on my MacBook, I tried this manual test in my dev docker container and failed for `/dev/sgx/enclave` is not found.

And I'm glad to include a test in my PR. 😄

**Comment by lkatalin** [comment]
@ziyi-yan Ah, sorry, that makes sense. I believe if you open a PR for this [repo](https://github.com/enarx/packet.com/blob/master/enarx.ks) with your public key, you can test on that machine.

**Comment by lkatalin** [comment]
@ziyi-yan Just following up, we have a template now for syscall tests in our `integration-tests` crate. The actual payload or code that is run in the Keep is [here](https://github.com/enarx/enarx/tree/master/integration-tests/src/bin). And [this](https://github.com/enarx/enarx/blob/master/integration-tests/tests/syscall_exit.rs) is an example of how the payloads are used in a test. As always, let me know if you have questions.
