### ISSUE TITLE
Rethink our use of openssl crate

### ISSUE THREAD

**Issue by kubkon** [enarx/enarx#753]
## Description

As reported by @npmccallum in #746:

Rethink openssl. The [`openssl`](https://github.com/sfackler/rust-openssl) crate is actively ignoring our PRs. Our crypto needs are very small in this crate. So we probably don't need the whole of openssl. We only need RSA and SHA256. So maybe we should use the [`rsa`](https://github.com/RustCrypto/RSA) and [`sha2`](https://github.com/RustCrypto/hashes) crates?

**Comment by npmccallum** [comment]
Note: I'm currently only suggesting this for the `sgx` crate.

**Comment by kubkon** [comment]
> Note: I'm currently only suggesting this for the `sgx` crate.

Noted! I'll have a look at our options soon-ish. I'm very much disheartened by the (un)responsiveness of `rust-openssl` maintainer(s) though!

**Comment by kubkon** [comment]
It seems that both [`rsa`] and [`hashes`] (`sha2` is part of `hashes` crate) were not security-audited and hence their use in production envs is strongly discouraged. For this reason, I'd be very hesitant to use them in a security-oriented project such as Enarx. @npmccallum do you think we could consider spelling out our own simple wrappers for `mbedtls` for just those bits that we need? This way, we wouldn't be dependent on `rust-openssl` *and* would use a library that has been audited.

[`rsa`]: https://github.com/RustCrypto/RSA
[`hashes`]: https://github.com/RustCrypto/hashes

**Comment by npmccallum** [comment]
@kubkon I'm aware.

SGX requires all applications to have a signature. This was done early on because Intel wanted to allow any third-party to contract with Intel to be able to launch SGX enclaves. However, Linux has rejected this approach and Intel responded with FLC.

The result is that while we need to generate this signature to make the hardware happy, it is mostly vestigial and isn't used for any security purpose. Therefore, we actually don't care about the security properties of the signature generated: just that it is a valid signature.

**Comment by MikeCamel** [comment]
I know this is only for this crate, but we have crypto needs (for HTTPS) in keep-runtime and host-components to consider as well.

**Comment by npmccallum** [comment]
@kubkon Did an initial pass at this and key generation using the `rsa` crate was very slow. I'm closing this issue for now.

**Comment by kubkon** [comment]
@npmccallum @MikeCamel That's correct. Generating keys for custom public key exponent is insanely slow. My guess is that's because `rsa` crate is using some custom, in-house generation algorithm tailored specifically to the default exponent of `65k`.
