### ISSUE TITLE
Description of the the issue

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#872]
For this wiki: https://github.com/enarx-archive/demo/tree/master/intel-sgx
Here are some points of SGX Remote Attestation need to add and update, but it is archived, could anyone help re-open it?

**Comment by lkatalin** [comment]
@xiaonan-INTC Thanks for wanting to share the information and I am glad to hear that you got the previous SGX attestation working after the issue in #843 . Since we are no longer supporting the attestation process described in that demo, we have archived it and we are not planning to add to the description you linked. There is currently no guarantee that it can be made to work reliably for others, as several of the dependencies have become outdated or diverged from what the archived code expects.

On our roadmap is a new SGX remote attestation process that you will see in the [enarx](https://github.com/enarx/enarx) repo. When this is complete, we will add detailed steps about how to use it in the README as well as on our wiki. It should be much easier to implement than what you have already done so far. Please look for this new process in the future!

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Thanks for wanting to share the information and I am glad to hear that you got the previous SGX attestation working after the issue in #843 . Since we are no longer supporting the attestation process described in that demo, we have archived it and we are not planning to add to the description you linked. There is currently no guarantee that it can be made to work reliably for others, as several of the dependencies have become outdated or diverged from what the archived code expects.
> 
> On our roadmap is a new SGX remote attestation process that you will see in the [enarx](https://github.com/enarx/enarx) repo. When this is complete, we will add detailed steps about how to use it in the README as well as on our wiki. It should be much easier to implement than what you have already done so far. Please look for this new process in the future!

@lkatalin 
Thanks for the info, looking forward to the new SGX RA, :)

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Thanks for wanting to share the information and I am glad to hear that you got the previous SGX attestation working after the issue in #843 . Since we are no longer supporting the attestation process described in that demo, we have archived it and we are not planning to add to the description you linked. There is currently no guarantee that it can be made to work reliably for others, as several of the dependencies have become outdated or diverged from what the archived code expects.
> 
> On our roadmap is a new SGX remote attestation process that you will see in the [enarx](https://github.com/enarx/enarx) repo. When this is complete, we will add detailed steps about how to use it in the README as well as on our wiki. It should be much easier to implement than what you have already done so far. Please look for this new process in the future!

BTW, @lkatalin 
What is the progress about new version SGX remote attestation process? And where could we get the source code in git?

**Comment by lkatalin** [comment]
@xiaonan-INTC We do not yet have complete code for the new SGX remote attestation process, but once we have the code ready I could make a note to let you know if you would like. Thanks for your interest.
