### ISSUE TITLE
Add trust architecture information to wiki

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#99]
Lots of text added here:

https://github.com/enarx/enarx/wiki/Trust-architecture

Please review.

**Comment by axelsimon** [comment]
Looks good to me.
I tried to add a bit of formatting, the idea being that more visual separation can help make the trusted/untrusted status is more visible.
Let me know if you'd like to revert.

Another thing I'd like is to re-use the numbering from the beginning of the article (1. VMM, 2. ukernel, 3. WASM 4. WASI) in the body of the article, especially the various headers I've added.
Currently however, that doesn't really work because even starting counting with CPU at `0.`, the kernel sits between "0. CPU" and "1. VMM".
Or we could count CPU as level -1 but that sounds a bit too hairy to me.

**Comment by axelsimon** [comment]
Just tried adding extra emojis to make even more visible. I think it works.

**Comment by MikeCamel** [comment]
Took some of the edits (included emojis), changed some formatting for conciseness.

**Comment by MikeCamel** [comment]
I think the numbering is just too complex.

**Comment by axelsimon** [comment]
Alright, let's give up on the numbering.

I think it looks better with the simplified formatting now. We can probably close this issue.
